### ISSUE TITLE
OpenAL not Loading on Linux

### ISSUE THREAD

**Issue by Snowiiii** [LWJGL/lwjgl3#780] opened 2022-07-19 20:38 UTC
### Version

3.3.2 (nightly)

### Platform

Linux x64

### JDK

openjdk-19 Oracle

### Module

OpenAL

### Bug description

OpenAL cant loading if I try to open a New Device

code:
```
String defaultDeviceName = alcGetString(0, ALC_DEFAULT_DEVICE_SPECIFIER);
            long j = ALC10.alcOpenDevice(defaultDeviceName);
```

### Stacktrace or crash log output

```shell
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

**Comment by Spasi** [comment] 2022-07-22 21:55
Hey @Snowiiii,

Could you please try the latest snapshot (3.3.2 build 2)? OpenAL Soft has been updated to `1.22.2`, which includes some fixes related to the audio backends on Linux.

**Comment by Snowiiii** [comment] 2022-07-22 22:15
@Spasi Have Updated but no difference same Error

**Comment by Spasi** [comment] 2022-10-22 19:31
Hey @Snowiiii,

I still cannot reproduce this and there haven't been any other reports about audio issues on Linux. Have you verified that PulseAudio and/or other audio components are configured correctly in your setup?

**Comment by Snowiiii** [comment] 2022-10-22 19:50
I have tested many things Up/Down grading LWJGL and even the change from Ubuntu to Arch does not have a effect,I guess the Problem is maybe that im using Pipewire and not PulseAudio

**Comment by Snowiiii** [comment] 2023-02-05 08:52
2023 - Still No Audio On:

- Arch
- Ubuntu
- PopOS
- Manjaro
- Fedora
I and my Friends tested them All

**Comment by Spasi** [comment] 2023-02-15 16:52
Hey @Snowiiii,

LWJGL `3.3.2-snapshot+9` is now available with OpenAL-Soft 1.23.0. I see some PipeWire-related fixes in the change log, could you please try it out?

(again, OpenAL works fine on my Linux machine with 1.23.0)

**Comment by Snowiiii** [comment] 2023-02-15 17:26
Hey i tested it our im current on Arch (6.1.11-arch1-1) and ye i tried to change some code but it dosnt work here the code & error

```java
  private static long openDevice() {
        OptionalLong optionallong;

        String device = ALC10.alcGetString(0, ALC10.ALC_DEFAULT_DEVICE_SPECIFIER);
        LOGGER.info("Audio Device: {}", device);
        optionallong = tryOpenDevice(device);

        if (optionallong.isEmpty()) {
            throw new IllegalStateException("Failed to open OpenAL device");
        } else {
            return optionallong.getAsLong();
        }
    }
```

```java
private static OptionalLong tryOpenDevice(@Nullable String p_193476_) {
        long i = ALC10.alcOpenDevice(p_193476_);
        return i != 0L && !ALUtils.checkALCError(i, "Open device") ? OptionalLong.of(i) : OptionalLong.empty();
    }
```

### Error

```
java.lang.IllegalStateException: Failed to open OpenAL device
	at net.minecraft.client.audio.SoundSystem.openDevice(SoundSystem.java:128) ~[main/:?]
	at net.minecraft.client.audio.SoundSystem.init(SoundSystem.java:45) ~[main/:?]
	at net.minecraft.client.audio.SoundEngine.load(SoundEngine.java:76) ~[main/:?]
	at net.minecraft.client.audio.SoundEngine.reload(SoundEngine.java:70) ~[main/:?]
	at net.minecraft.client.audio.SoundHandler.onResourceManagerReload(SoundHandler.java:60) ~[main/:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:87) ~[main/:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:338) ~[main/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:271) ~[main/:?]
	at net.minecraft.client.main.Main.main(Main.java:108) ~[main/:?]
	at Start.main(Start.java:8) ~[main/:?]
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

**Comment by Spasi** [comment] 2023-03-04 16:29
Hey @Snowiiii,

Bad news I'm afraid. Looks like we've been building OpenAL-Soft without the Pipewire backend, because it is not available on Ubuntu 18.04 (the version used by LWJGL-CI). I've tried several approaches, but couldn't get OpenAL-Soft to build with Pipewire on anything other than Ubuntu 22.04 amd64. That is, even on 22.04, the arm64 & armhf builds fail.

One option you have is building your own OpenAL-Soft binary and deploying your application with that. For reference, the LWJGL-CI workflow file is [here](https://github.com/LWJGL-CI/openal-soft/blob/master/.github/workflows/lwjgl.yml). At runtime, you can override the loaded library with `Configuration.OPENAL_LIBRARY_NAME` (or `-Dorg.lwjgl.openal.libname`).

**Comment by Snowiiii** [comment] 2023-03-04 16:44
:c

**Comment by Snowiiii** [comment] 2023-03-19 22:56
Same Result Bro :c

**Comment by Spasi** [comment] 2023-03-20 10:26
@Snowiiii could you please post the output you get when running with the above build? Specifically, with:

```
export ALSOFT_LOGLEVEL=3
java <your app params here> -Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true -Dorg.lwjgl.openal.libname=<path to custom build>/libopenal.so
```

**Comment by Snowiiii** [comment] 2023-03-20 10:48
```
[LWJGL] Version: 3.3.2-snapshot+11
	 OS: Linux v6.2.7-arch1-1
	JRE: Linux amd64 17.0.6
	JVM: OpenJDK 64-Bit Server VM v17.0.6+1-b653.34 by JetBrains s.r.o.
[LWJGL] Loading JNI library: lwjgl
	Module: org.lwjgl
	Using SharedLibraryLoader...
	Found at: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/liblwjgl.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/liblwjgl.so
[LWJGL] Loading library: glfw
	Module: org.lwjgl.glfw
	Using SharedLibraryLoader...
	Found at: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/libglfw.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/libglfw.so
[LWJGL] Loading JNI library: lwjgl_opengl
	Module: org.lwjgl.opengl
	Using SharedLibraryLoader...
	Found at: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/liblwjgl_opengl.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/liblwjgl_opengl.so
[LWJGL] Loading library: libGL.so.1
	Module: org.lwjgl.opengl
	libGL.so.1 not found in org.lwjgl.librarypath=/tmp/lwjgl_snowii/3.3.2-snapshot+11/x64
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] MemoryUtil allocator: StdlibAllocator
[LWJGL] Java 9 text decoding enabled
	Loaded from system paths: /usr/lib/x86_64-linux-gnu/libGL.so.1
[LWJGL] Java 10 multiplyHigh enabled
[LWJGL] Java 9 check intrinsics enabled

[LWJGL] Loading library: openal
	Module: org.lwjgl.openal
	Using SharedLibraryLoader...
	Found at: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/libopenal.so
	Loaded from org.lwjgl.librarypath: /tmp/lwjgl_snowii/3.3.2-snapshot+11/x64/libopenal.so
[LWJGL] [ALC] ALC_SOFT_reopen_device was reported as available but an entry point is missing.
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

**Comment by Spasi** [comment] 2023-03-20 11:57
@Snowiiii Based on the output, it seems like `libopenal.so` is loaded from `3.3.2-snapshot+11`. The LWJGL snapshot does not yet have the Pipewire backend. Have you overwritten that file with the build I linked above?

Also, there should be a lot more output from the OpenAL Soft logging enabled with `export ALSOFT_LOGLEVEL=3`. The first two lines should be:

> [ALSOFT] (II) Initializing library v1.23.0- 
> [ALSOFT] (II) Supported backends: pipewire, pulse, alsa, oss, jack, port, null, wave

**Comment by Snowiiii** [comment] 2023-03-22 16:52
![image](https://user-images.githubusercontent.com/71594357/226978860-eacbeb66-07a0-4dd4-b224-57df9a82faa7.png)

So here how my Intellij Startup looks, The Problem is that its still loading OpenAL from LWJGL and not the custom Build, And the Secound Problem is that i dont really understand where i should put in ```export ALSOFT_LOGLEVEL=3``` i had but it in as Env var but Nothing changed

**Comment by Spasi** [comment] 2023-03-22 19:03
Hey @Snowiiii,

Try setting `-Dorg.lwjgl.openal.libname=` to the absolute path of the custom OpenAL build.

Also, the `export` command should be removed from the `Environment variables` field. It should be just `ALSOFT_LOGLEVEL=3`.

**Comment by Snowiiii** [comment] 2023-03-23 17:47
Okay now we have more Output yes

```
[LWJGL] Loading library: /home/snowii/Documents/development/java/Vent-Client-1.8.9-Hack/run/libopenal.so
	Module: org.lwjgl.openal
	Success
[LWJGL] [ALC] ALC_SOFT_reopen_device was reported as available but an entry point is missing.
[ALSOFT] (II) Initializing library v1.23.0- 
[ALSOFT] (II) Supported backends: pipewire, pulse, alsa, oss, jack, port, null, wave
[ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
[ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /app/etc/xdg/alsoft.conf...
[ALSOFT] (II) Loading config /home/snowii/.alsoftrc...
[ALSOFT] (II) Loading config /home/snowii/.var/app/com.jetbrains.IntelliJ-IDEA-Community/config/alsoft.conf...
[ALSOFT] (II) Got binary: "/app/idea-IC/jbr/bin", "java"
[ALSOFT] (II) Loading config /app/idea-IC/jbr/bin/alsoft.conf...
[ALSOFT] (II) Key disable-cpu-exts not found
[ALSOFT] (II) Vendor ID: "AuthenticAMD"
[ALSOFT] (II) Name: "AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx"
[ALSOFT] (II) Extensions: +SSE +SSE2 +SSE3 +SSE4.1
[ALSOFT] (II) Key rt-prio not found
[ALSOFT] (II) Key rt-time-limit not found
[ALSOFT] (II) Key game_compat/reverse-x not found
[ALSOFT] (II) Key game_compat/reverse-y not found
[ALSOFT] (II) Key game_compat/reverse-z not found
[ALSOFT] (II) Key game_compat/nfc-scale not found
[ALSOFT] (II) Key resampler not found
[ALSOFT] (II) Key uhj/decode-filter not found
[ALSOFT] (II) Key uhj/filter not found
[ALSOFT] (II) Key uhj/encode-filter not found
[ALSOFT] (II) Key trap-al-error not found
[ALSOFT] (II) Key trap-alc-error not found
[ALSOFT] (II) Key reverb/boost not found
[ALSOFT] (II) Key drivers not found
[ALSOFT] (WW) PipeWire version "0.3.66" too old (0.3.67 or newer required)
[ALSOFT] (WW) Failed to initialize backend "pipewire"
[ALSOFT] (II) Key pulse/spawn-server not found
[ALSOFT] (WW) Failed to initialize backend "pulse"
[ALSOFT] (II) Initialized backend "alsa"
[ALSOFT] (II) Added "alsa" for playback
[ALSOFT] (II) Added "alsa" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Opening playback device "OpenAL Soft"
[ALSOFT] (II) Key alsa/device not found
[ALSOFT] (II) Opening device "default"
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

[ALSOFT] (WW) Failed to open playback device: Could not open ALSA device "default"
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
[ALSOFT] (II) Freeing device 0x7f7b4d951f80
[18:43:10] [Client thread/INFO]: Audio Device: OpenAL Soft
```

**Comment by Spasi** [comment] 2023-03-23 20:24
That's great @Snowiiii. A new build is up, could you [download it](https://build.lwjgl.org/nightly/linux/x64/libopenal.so) and try again please?

**Comment by Snowiiii** [comment] 2023-03-23 20:27
> 

Same Result :c

**Comment by Spasi** [comment] 2023-03-23 21:05
Hmm, no change at this line?

> [ALSOFT] (WW) PipeWire version "0.3.66" too old (0.3.67 or newer required)

The new build was built with PipeWire 0.3.50.

**Comment by Snowiiii** [comment] 2023-03-23 21:07
Ye looks like 0.3.67 or newer is required

**Comment by Spasi** [comment] 2023-03-23 21:22
@Snowiiii I checked again, it should be 0.3.50. Are you sure you downloaded the new build and replaced the old one?

**Comment by Snowiiii** [comment] 2023-03-25 16:21
```
[ALSOFT] (II) Found PipeWire version "0.3.66" (0.3.50 or newer)
```

**Comment by Snowiiii** [comment] 2023-03-25 16:21
```
[ALSOFT] (WW) Failed to initialize backend "pipewire"
[ALSOFT] (II) Key pulse/spawn-server not found
[ALSOFT] (WW) Failed to initialize backend "pulse"
[ALSOFT] (II) Initialized backend "alsa"
[ALSOFT] (II) Added "alsa" for playback
[ALSOFT] (II) Added "alsa" for capture
[ALSOFT] (II) Key excludefx not found
[ALSOFT] (II) Key default-reverb not found
[ALSOFT] (II) Opening playback device "OpenAL Soft"
[ALSOFT] (II) Key alsa/device not found
[ALSOFT] (II) Opening device "default"
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

[ALSOFT] (WW) Failed to open playback device: Could not open ALSA device "default"
[ALSOFT] (WW) Error generated on device (nil), code 0xa004
[ALSOFT] (II) Freeing device 0x7fd3d8b73520
```

**Comment by Spasi** [comment] 2023-03-26 20:45
FWIW, I was able to get it working on my Linux machine. `ALCDemo` output:

```
[ALSOFT] (II) Found PipeWire version "0.3.58" (0.3.50 or newer)
[ALSOFT] (II) Key pipewire/assume-audio not found
[ALSOFT] (II) Ignoring metadata "settings"
[ALSOFT] (II) Ignoring metadata "route-settings"
[ALSOFT] (II) Ignoring node class Midi/Bridge
[ALSOFT] (II) Initialized backend "pipewire"
[ALSOFT] (II) Added "pipewire" for playback
[ALSOFT] (II) Added "pipewire" for capture
```

`pactl info` output:

```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 264
Tile Size: 65472
User Name: *****
Host Name: *****
Server Name: PulseAudio (on PipeWire 0.3.58)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_26_00.1.hdmi-stereo-extra1
Default Source: alsa_output.pci-0000_26_00.1.hdmi-stereo-extra1.monitor
```

Maybe you could try another machine? Or reinstalling Pipewire and/or pulseaudio? Afaict the pulse library is required, because Pipewire is using it as a backend.

**Comment by Spasi** [comment] 2023-04-01 14:27
We've verified that the PipeWire backend works now, so closing this.

**Closed by Spasi** 2023-04-01 14:27 UTC
Labels: Type: Maintenance
