### ISSUE TITLE
Assimp joint transformation issue in Early Access build (3.3.0)

### ISSUE THREAD

**Issue by cpope9141** [LWJGL/lwjgl3#656] opened 2021-06-02 21:36 UTC
### Environment

* LWJGL version: `3.3.0` 
* LWJGL build #: `11`
* Java version: `16.0.1`
* Platform: `Windows`
* Module: `assimp`

### Description

I apologize if this is not the correct place to report issues in non-release builds. If this is the case, please redirect me.

I am trying the 3.3.0 early access build and am seeing an issue with Assimp importing joint transformations. Animated models appear skewed and stretched 90 degrees in the vertical plane. The poses are timed correctly, just skewed and stretched. Static models (no joints or vertex weights) appear to import without issue.

The Assimp module from the release build (3.2.3) does not have this issue. Could it be an Assimp configuration change that I do not know about?

**Comment by Kerai** [comment] 2021-06-07 11:01
can you give example model?

**Comment by httpdigest** [comment] 2021-06-07 11:10
> I apologize if this is not the correct place to report issues in non-release builds.

This is likely not the right place to report this issue, because it is an issue with Assimp itself and not LWJGL. LWJGL merely maps between Java and C API calls. LWJGL has no business in what Assimp actually _does_ when importing a model.
Please report with Assimp and optimally provide them with a minimal, complete and verifiable example / test case.

**Comment by cpope9141** [comment] 2021-06-07 13:38
> can you give example model?

I can provide the FBX file with the model and animations, but it doesn't look like github will allow me to attach it. How do reporters usually provide test cases or examples?

**Comment by cpope9141** [comment] 2021-06-07 13:49
@httpdigest, I understand that LWJGL is only providing bindings to the lower level API. Can you tell me what versions of Assimp are wrapped by LWJGL 3.2.3 and 3.3.0, respectively? That would probably be helpful when reporting the issue to Assimp, since the issue first appeared in whatever version 3.3.0 wraps.

Is there a general way of determining what version of a lower level binding is in LWJGL?

**Comment by httpdigest** [comment] 2021-06-07 13:53
The LWJGL 3.3.0-SNAPSHOT currently includes version 5.0.1 of Assimp. In particular, the commit https://github.com/assimp/assimp/commit/75144dd7fd9581888223041f62244d86198d5dca
You can investigate the LWJGL 3 natives jar file of Assimp and you'll see a `assimp.dll.git` file in it that tells the Git commit hash.

**Comment by httpdigest** [comment] 2021-09-05 13:23
Closing as it's not an issue with LWJGL itself, and likely with Assimp, as mentioned above.

**Closed by httpdigest** 2021-09-05 13:23 UTC

**Comment by cpope9141** [comment] 2022-01-13 00:20
I understand that this is not a LWJGL issue, but in 3.3.0 release, this issue is still present in the Assimp library.

**Comment by httpdigest** [comment] 2022-01-13 10:02
Thanks for informing us that the issue is likely still present in the current Assimp library version. LWJGL will always try to update to the most up-to-date version of its supported libraries in a timely manner. So, we can only wait for the next version of Assimp to come out with a fix for that issue (apart from providing a PR in the upstream repo to fix it ourselves, of course), which will then make it into a new LWJGL snapshot/nightly build or release eventually.
Though, I stand by my opinion that tracking every possible/conceivable bug in an upstream library also with an LWJGL bug ticket is not useful, since (as I mentioned) LWJGL will pick up with recent/new library versions anyway. So, these LWJGL bug tickets for thirdparty bugs would only be useful for being reminded of looking for updates of those third party library versions (which will happen periodically anyway).
