### ISSUE TITLE
Unexpected GLFWKeyCallback.invoke -1 key parameter

### ISSUE THREAD

**Issue by Lypio** [LWJGL/lwjgl3#566] opened 2020-06-09 18:02 UTC
### Environment

* LWJGL version: `3.2.3` 
* Java version: `java.version:13.0.2`
* Platform: `Windows`
### Description
The parameter "key" of the invoke method of a GLFWKeyCallback equals -1 when pressing "Fn + <Any Hotkey>" (for example "Fn + F11", F11 beeing my Pause Hotkey) instead of beeing equal to the corresponding hotkey (GLFW_KEY_PAUSE=284 in my case). Note that this key combination works fine in other apps.

Here is the code :

boolean[] keys = new boolean[GLFW.GLFW_KEY_LAST];
GLFWKeyCallback keyboardCallback = new GLFWKeyCallback() {
  @Override
  public void invoke(long window, int key, int scancode, int action, int mods) {
    // ISSUE :  When pressing Fn + F11, key= -1 instead of 284, causing ArrayIndexOutOfBoundsException if not handled properly
    try {
      keys[key] = (action != GLFW.GLFW_RELEASE);
    }catch (ArrayIndexOutOfBoundsException e){ // handling unexpected -1 key value
      System.err.println("Error : Unsupported key.");
    }
  }
};

**Comment by octylFractal** [comment] 2020-06-09 18:55
I cannot reproduce this with a small sample program:
https://gist.github.com/octylFractal/a01e323a5a927843e92934f67669448b gives me:
```
GLFW Key Callback: Action: PRESS, Name: null, Raw Key/Scancode: 284/69
GLFW Key Callback: Action: RELEASE, Name: null, Raw Key/Scancode: 284/69
```
for my pause key on my physical keyboard. Unfortunately my laptop keyboard doesn't have a Fn combo for Pause, but it does have one for Home, which gives me:
```
GLFW Key Callback: Action: PRESS, Name: null, Raw Key/Scancode: 268/327
GLFW Key Callback: Action: RELEASE, Name: null, Raw Key/Scancode: 268/327
```
So this looks fine from the LWJGL side.

I suspect this is actually a GLFW bug (you're getting GLFW_KEY_UNKNOWN since GLFW doesn't know what key that is for some reason), and you should provide more details to them. https://github.com/glfw/glfw/issues/730 is the closest issue I could find, but it's not quite the same.

Aside from that, you _should_ handle GLFW_KEY_UNKNOWN properly, it is something that can come up at any time, and your code should handle it cleanly rather than using AIOOBE. A good idea is to use the scancode instead, which still works even if the key does not get read properly by GLFW.

**Comment by Lypio** [comment] 2020-06-09 20:04
Thanks for your quick answer!

I tried some more with my code and noticed that the volume buttons of my USB keyboard (which doesn't require Fn to be pressed) set "key" to GLFW_KEY_UNKNOWN as well. I then tried the volume keys of my laptop keyboard, leading to the same issue. 

Then I tried with your kotlin sample code and appreciate the idea of using scancode ; however, it doesn't seem to work better as I get scancode=256 for each of the unknown presses.
Here's what I get : 
GLFW Key Callback: Action: PRESS, Name: t, Raw Key/Scancode: 84/20 // t, works fine
GLFW Key Callback: Action: PRESS, Name: e, Raw Key/Scancode: 69/18 // e, works fine
GLFW Key Callback: Action: PRESS, Name: s, Raw Key/Scancode: 83/31 // s, works fine
GLFW Key Callback: Action: PRESS, Name: t, Raw Key/Scancode: 84/20 // t, works fine
GLFW Key Callback: Action: PRESS, Name: \], Raw Key/Scancode: -1/256 // vol up, going wrong
GLFW Key Callback: Action: PRESS, Name: \], Raw Key/Scancode: -1/256 // vol down, going wrong
GLFW Key Callback: Action: PRESS, Name: \], Raw Key/Scancode: -1/256 // Fn + Pause, going wrong

For further investigation, I wrote an EventHandler in Javafx and I got KeyCode.UNDEFINED and as the javadoc mentions : "This value is used to indicate that the keyCode is unknown.". 
Therefore, I don't think this issue is actually of any kind in relation with LWJGL, as you expected.
Now, do you have an idea how to fix my issue, as those keys just work fine in any app (Spotify f.e.)?
Also, should I close this thread? Thanks again for your help!

**Comment by XenoAmess** [comment] 2020-06-10 03:31
> Thanks for your quick answer!
> 
> I tried some more with my code and noticed that the volume buttons of my USB keyboard (which doesn't require Fn to be pressed) set "key" to GLFW_KEY_UNKNOWN as well. I then tried the volume keys of my laptop keyboard, leading to the same issue.
> 
> Then I tried with your kotlin sample code and appreciate the idea of using scancode ; however, it doesn't seem to work better as I get scancode=256 for each of the unknown presses.
> Here's what I get :
> GLFW Key Callback: Action: PRESS, Name: t, Raw Key/Scancode: 84/20 // t, works fine
> GLFW Key Callback: Action: PRESS, Name: e, Raw Key/Scancode: 69/18 // e, works fine
> GLFW Key Callback: Action: PRESS, Name: s, Raw Key/Scancode: 83/31 // s, works fine
> GLFW Key Callback: Action: PRESS, Name: t, Raw Key/Scancode: 84/20 // t, works fine
> GLFW Key Callback: Action: PRESS, Name: �\�]�, Raw Key/Scancode: -1/256 // vol up, going wrong
> GLFW Key Callback: Action: PRESS, Name: �\�]�, Raw Key/Scancode: -1/256 // vol down, going wrong
> GLFW Key Callback: Action: PRESS, Name: �\�]�, Raw Key/Scancode: -1/256 // Fn + Pause, going wrong
> 
> For further investigation, I wrote an EventHandler in Javafx and I got KeyCode.UNDEFINED and as the javadoc mentions : "This value is used to indicate that the keyCode is unknown.".
> Therefore, I don't think this issue is actually of any kind in relation with LWJGL, as you expected.
> Now, do you have an idea how to fix my issue, as those keys just work fine in any app (Spotify f.e.)?
> Also, should I close this thread? Thanks again for your help!

simply change your key array to a map.

**Comment by httpdigest** [comment] 2020-08-14 23:56
Closing because LWJGL has no influence in how GLFW reports keys.

**Closed by httpdigest** 2020-08-14 23:56 UTC
Labels: Type: Question
