### ISSUE TITLE
The package org.lwjgl is accessible from more than one module

### ISSUE THREAD

**Issue by DesertCookie** [LWJGL/lwjgl3#341] opened 2017-10-21 09:17 UTC
"The package org.lwjgl is accessible from more than one module: org.lwjgl, org.lwjgl.glfw, org.lwjgl.openal, org.lwjgl.opengl, org.lwjgl.stb"
This is the error I get in Eclipse, when adding the import "org.lwjgl.BufferUtils". All my BufferUtils are underlines red and I couldn't find anyone else with this exact problem! I don't know much about the new module system and I'm quiete confused. Is there a known solution already?
_Using Java 9, LWJGL 3.1.4 stable, Eclipse Oxygen 4.7.1a, all other LWJGL/OpenGL/GLFW classes work fine._

**Comment by TheMrMilchmann** [comment] 2017-10-21 14:23
This is likely a duplicate of #338.

It does look like it is a bug in Oxygen 4.7.1a. Take a look at [this]((https://github.com/LWJGL/lwjgl3/issues/338#issuecomment-334400562) for a more detailed answer.

**Comment by philipguin** [comment] 2017-12-21 20:33
Any other possible workarounds for this? Just slapping LWJGL into the classpath results in a whole bunch of  imports getting "The type XXX is not accessible," which is even worse than the original issue. (It's as though sticking it on the classpath only results in nothing getting exported.)

Using Java 9, LWJGL 3.1.5 stable, Eclipse Oxygen 4.7.2.

**Comment by kevsters** [comment] 2018-01-10 07:13
Can you explain what you did to get around this?  I tried to add the JARS to the classpath, but I think I might have done it wrong, because the error message is still there.

**Comment by kevsters** [comment] 2018-01-10 07:28
nvr mind I got it.  Wasn't adding it to the classpath through eclipse.

**Closed** 2018-02-04 15:38 UTC
Labels: Type: Question
