### ISSUE TITLE
WGPU bindings

### ISSUE THREAD

**Issue by jalexcole** [LWJGL/lwjgl3#944] opened 2023-11-15 15:25 UTC
### Library

WebGpu-Native or Dawn

### Project page

https://github.com/gfx-rs/wgpu-native

### Source repository

https://github.com/gfx-rs/wgpu-native

### Platforms

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### Description

Webgpu is a metal like library that works inside the web browser. WebGpu-native allows for the webgpu to be used outside of the browser inside of native enviroments. To use these enviroments the library sits on top of DirectX, Metal, and Vulkan. There are two seperate implementations of wgpu for native, one called WebGpu native written in rust with a C ABI, and Dawn that is written in C++. 

This was previously mentioned several years ago in an old issue: #614

**Comment by DontingK** [comment] 2023-11-28 07:55
I also hope to have the support of webgpu.  Webgpu will be a very good cross-platform solution.

**Comment by Laxystem** [comment] 2024-12-14 13:16
Any updates? Vulkan is cursed a mess to get up and running with Kotlin, and OpenGL does not support concurrency.

**Comment by jalexcole** [comment] 2024-12-14 16:17
I looked into creating bindings but did not get past the generator script off of the header file.

**Comment by TheMrMilchmann** [comment] 2024-12-23 21:17
Closing this as a duplicate of #614.

**Closed by TheMrMilchmann** 2024-12-23 21:17 UTC
Labels: duplicate, Type: Enhancement
