### ISSUE TITLE
No module-info.class file was generated

### ISSUE THREAD

**Issue by Annette0127** [LWJGL/lwjgl3#879] opened 2023-04-22 05:38 UTC
### Question

Hi! 
We tried to build the project according to the guidance, but it failed at the step of ant compile-native. During the process, some .class files are generated besides `module-info.class` file, which should be generated by compiling the `module-info.java` file. And we do notice that, on your release version, you have `module-info.class` file inside jars. So we are wondering whether there's something we need to be extra careful about while building your systems if we want to obtain module-info.class file?

The way we are trying to build the system:
```
git clone https://github.com/LWJGL/lwjgl3.git
cd lwjgl3
ant init
ant compile-templates 
ant generate 
ant compile 
ant compile-native (failed)
```

Thank you for your time ahead! 😊

**Comment by Spasi** [comment] 2023-04-23 14:24
Hey @Annette0127,

The `module-info` classes are generated during the `release` target, when building with a JDK 9+ JDK. They're then stored inside the jar files, under the `META-INF/versions/9` folder (see multi-release jars for why this works). They're not used for anything else, lwjgl3 is Java 8 compatible.

Your build is failing earlier though, in the native compilation target. If you could provide more information (OS, native compiler, build output), I might be able to help with resolving the issue.

**Comment by Annette0127** [comment] 2023-04-24 01:23
Hello @Spasi, thank you very much for the information on when `module-info.class` was generated!

As for my building failure, more details are as follows:

- OS: macOS Ventura Version 13.3.1

- Native compiler: I am not quite sure what you want to know here. If you are asking about my gcc compiler, it is `Apple clang version 14.0.3 (clang-1403.0.22.14.1)`

- Build output: 
```
compile-native:

compile-native-platform:
 [SDK Root] <path to SDKs>/MacOSX13.3.sdk
 [Compiler] <Path to the project>/lwjgl3/modules/lwjgl/core/src/generated/c/org_lwjgl_system_JNI.c:20:35: fatal error: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
 [Compiler]     return (jshort)((uint16_t (*) ())(uintptr_t)__functionAddress)();
 [Compiler]                                   ^
 [Compiler]                                    void
 [Compiler] 1 error generated.

BUILD FAILED
<Path to the project>/lwjgl3/build.xml:574: The following error occurred while executing this line:
<Path to the project>/lwjgl3/config/macos/build.xml:139: The following error occurred while executing this line:
<Path to the project>/lwjgl3/config/macos/build.xml:82: The following error occurred while executing this line:
<Path to the project>/lwjgl3/config/macos/build.xml:33: apply returned: 1
```

**Comment by Spasi** [comment] 2023-04-24 11:20
Hey @Annette0127, yeah that's perfect.

Looks like a new Clang warning (treated as error because we build with `-Werror`) after the latest Xcode update. I can reproduce it locally and will get it fixed soon.

**Comment by Annette0127** [comment] 2023-04-24 14:44
Hey @Spasi, thank you very much for your help. 😊

**Comment by Annette0127** [comment] 2023-04-28 04:44
Hi @Spasi, I apologize for reaching out again, but I was curious about the reason behind the generation of `module-info` classes during the `release` target instead of the `compile` target, alongside other .java files. There seems to be some kind of design advantage of compiling them separately, but I am not sure what exactly that may be.

**Comment by Spasi** [comment] 2023-04-28 10:30
Hey, I wouldn't say there's a design advantage. They are simply not needed for anything, up to the point of building the final jar artifacts. There is no target that uses the module path (including `tests` and `demo`). All development and testing is done on JDK 8, so it is not even possible to compile the `module-info` classes without switching to a newer JDK.

However, all jar artifacts (both Java and `-native`) contain a `module-info` class, so LWJGL is fully compatible with the Java module system. Simply adding an `Automatic-Module-Name` to the JAR manifest was not enough because of `jlink`, it requires explicit modules for all dependencies. JDK 8 and legacy tools simply ignore the `module-info` classes because they're "hidden" under `META-INF/versions/9`.

**Closed** 2023-04-30 16:10 UTC
Labels: Type: Bug

**Comment by Annette0127** [comment] 2023-05-04 04:15
@Spasi Thank you very much for your answer; it has been really helpful! 😊
