### ISSUE TITLE
Wrong handle for glSpecializeShader

### ISSUE THREAD

**Issue by loginmen** [LWJGL/lwjgl3#551] opened 2020-04-14 09:09 UTC
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `1.8`
* Platform: `Windows`
* Module: `opengl 46`

In c++ function has prototype 
```cpp
void glSpecializeShader(GLuint shader​, const GLchar *pEntryPoint​, GLuint numSpecializationConstants​, const GLuint *pConstantIndex​, const GLuint *pConstantValue​);
```
can be used by
```cpp
glSpecializeShader(id​, "main"​, 0, nullptr, nullptr​);
```
But this imposible in java, because missed `GLuint numSpecializationConstants` parameter. How use this function without specialization constants? And how pass null?
If use IntBuffers with 0 then give 
```
API:ERROR[HIGH](1281): GL_INVALID_VALUE error generated. Failed to parse Spirv binary
Error compiling Shader code: (0) : error C8005: SPIR-V: Invalid spec constant ID provided in specialization info
```
If use with `new int[] {}` then give
```
API:ERROR[HIGH](1281): GL_INVALID_VALUE error generated. One or more handles do not refer to an object generated by OpenGL.
API:ERROR[HIGH](1281): GL_INVALID_VALUE error generated. One or more handles do not refer to an object generated by OpenGL.
API:ERROR[HIGH](1281): GL_INVALID_VALUE error generated. Object handle does not refer to an object generated by OpenGL.
```
Shaders work fine with vulkan and no have errors

**Comment by TheMrMilchmann** [comment] 2020-04-14 10:34
Hi, the `numSpecializationConstants​` parameter is automatically assigned to the number of elements in `pConstantIndex​` by LWJGL. The actual issue here is that the function should accept `null` for both `pConstantIndex​` and `pConstantValue​`.

In the meantime you should be able to work around this by passing zero-capacity buffers:
```
try (MemoryStack stack = MemoryStack.stackPush()) {
    glSpecializeShader(id​, "main", stack.mallocInt(0), stack.mallocInt(0));
}
```

**Comment by Spasi** [comment] 2020-04-14 10:39
Marking as a bug, because `pConstantIndex` and `pConstantValue` should be nullable in the LWJGL bindings. However, I think the error is caused by something else. Passing zero-length `IntBuffer` arguments should be equivalent, `numSpecializationConstants` will receive the correct value (`0`) and the `const GLuint *` pointers won't be dereferenced.

You could try the following code to verify:

```
import static org.lwjgl.opengl.GL46.*;
import static org.lwjgl.system.MemoryStack.*;
import static org.lwjgl.system.MemoryUtil.*;
// ...
try (MemoryStack s = stackPush()) {
    ByteBuffer pEntryPoint = s.UTF8("main");
    nglSpecializeShader(shader, memAddress(pEntryPoint), 0, NULL, NULL);
}
```

**Comment by loginmen** [comment] 2020-04-14 10:57
Found error, but i use example from khronos wiki how load spir-v
https://www.khronos.org/opengl/wiki/SPIR-V
```java
int shaderProgram = glCreateProgram();
		if (shaderProgram == 0) {
			throw new RuntimeException("Could not create Shader");
		}
		int shaderId = glCreateShader(shaderType);
		if (shaderId == 0) {
			throw new RuntimeException("Error creating shader. Type: " + shaderType);
		}
		try (MemoryStack stack = stackPush()) {
			
			IntBuffer ib1 = stack.mallocInt(1);
			ib1.put(shaderId).flip();
			ByteBuffer bb = stack.malloc(shaderBytes.length);
			bb.put(shaderBytes).flip();
			glShaderBinary(ib1, GL_SHADER_BINARY_FORMAT_SPIR_V, bb);
			glSpecializeShader(shaderId, stack.UTF8("main"), stack.mallocInt(0), stack.mallocInt(0));
		}
		if (glGetShaderi(shaderId, GL_COMPILE_STATUS) == GL_FALSE) {
            throw new RuntimeException("Error compiling Shader code: " + glGetShaderInfoLog(shaderId, 1024));
        }
		//glDeleteShader(shaderId);
		glProgramParameteri(shaderProgram, GL_PROGRAM_SEPARABLE, GL_TRUE);
		glAttachShader(shaderProgram, shaderId);
		glLinkProgram(shaderProgram);
		glDetachShader(shaderProgram, shaderId);
		if (glGetProgrami(shaderProgram, GL_VALIDATE_STATUS) == 0) {
            throw new RuntimeException("Error validating shader: " + glGetProgramInfoLog(shaderId, 1024));
        }
		return shaderProgram;
```
they delete shader before attach in example

**Closed** 2020-05-02 21:20 UTC
Labels: Type: Bug
