### ISSUE TITLE
Unexpected Yoga calculation results

### ISSUE THREAD

**Issue by SpinyOwl** [LWJGL/lwjgl3#355] opened 2017-11-25 14:16 UTC
### Environment

* LWJGL version: `3.1.5-SNAPSHOT` 
* LWJGL build #: `lwjgl-3.1.5-20171122.004553-1`
* Java version: `1.8.0_144`
* Platform: `Windows`
* Module: `Yoga`

### Description

I am trying to make border layout
![Border layout concept](https://user-images.githubusercontent.com/6123702/32548707-0e431cbc-c4a0-11e7-8d7f-bbee8ea455a0.png)
 and found next issue:
![animation](https://user-images.githubusercontent.com/6692636/33235525-db69dae8-d24a-11e7-89a4-2791360d16f9.gif)

Here is my test code:

```java
    private Vector2f minTop = new Vector2f(200, 20);
    private Vector2f minBottom = new Vector2f(200, 20);
    private Vector2f minLeft = new Vector2f(100, 20);
    private Vector2f minRight = new Vector2f(120, 20);
    private Vector2f minCenter = new Vector2f(50, 50);

    private Vector2f maxTop = new Vector2f(Float.MAX_VALUE, 120);
    private Vector2f maxBottom = new Vector2f(Float.MAX_VALUE, 80);
    private Vector2f maxLeft = new Vector2f(300, Float.MAX_VALUE);
    private Vector2f maxRight = new Vector2f(200, Float.MAX_VALUE);
    private Vector2f maxCenter = new Vector2f(Float.MAX_VALUE, Float.MAX_VALUE);

    private Vector4f midRow = new Vector4f();
    private Vector4f top = new Vector4f();
    private Vector4f bottom = new Vector4f();
    private Vector4f left = new Vector4f();
    private Vector4f center = new Vector4f();
    private Vector4f right = new Vector4f();

    private Vector2f size = new Vector2f();

    protected void update() {
        long rootNode = Yoga.YGNodeNew();

        long mNode = Yoga.YGNodeNew();

        long tNode = Yoga.YGNodeNew();
        long lNode = Yoga.YGNodeNew();
        long cNode = Yoga.YGNodeNew();
        long rNode = Yoga.YGNodeNew();
        long bNode = Yoga.YGNodeNew();

        Yoga.YGNodeInsertChild(rootNode, tNode, 0);
        Yoga.YGNodeInsertChild(rootNode, mNode, 1);
        Yoga.YGNodeInsertChild(rootNode, bNode, 2);

        Yoga.YGNodeInsertChild(mNode, lNode, 0);
        Yoga.YGNodeInsertChild(mNode, cNode, 1);
        Yoga.YGNodeInsertChild(mNode, rNode, 2);

        Yoga.YGNodeStyleSetFlexDirection(rootNode, Yoga.YGFlexDirectionColumn);
        Yoga.YGNodeStyleSetAlignItems(rootNode, Yoga.YGAlignStretch);
        Yoga.YGNodeStyleSetJustifyContent(rootNode, Yoga.YGJustifySpaceBetween);

        Yoga.YGNodeStyleSetFlexDirection(mNode, Yoga.YGFlexDirectionRow);
        Yoga.YGNodeStyleSetAlignItems(mNode, Yoga.YGAlignStretch);
        Yoga.YGNodeStyleSetJustifyContent(mNode, Yoga.YGJustifySpaceBetween);

        float midMaxOfMin = Math.max(Math.max(minLeft.y, minCenter.y), minRight.y);
        Yoga.YGNodeStyleSetMinHeight(mNode, midMaxOfMin);
        Yoga.YGNodeStyleSetMaxHeight(mNode, Float.MAX_VALUE);

        Yoga.YGNodeStyleSetWidth(mNode, size.x);

        Yoga.YGNodeStyleSetFlexGrow(mNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(mNode, 1);

        Yoga.YGNodeStyleSetMaxWidth(tNode, maxTop.x);
        Yoga.YGNodeStyleSetMaxHeight(tNode, maxTop.y);
        Yoga.YGNodeStyleSetMinWidth(tNode, minTop.x);
        Yoga.YGNodeStyleSetMinHeight(tNode, minTop.y);
        Yoga.YGNodeStyleSetFlexGrow(tNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(tNode, 1);
        Yoga.YGNodeStyleSetWidth(tNode, size.x);

        Yoga.YGNodeStyleSetMaxWidth(bNode, maxBottom.x);
        Yoga.YGNodeStyleSetMaxHeight(bNode, maxBottom.y);
        Yoga.YGNodeStyleSetMinWidth(bNode, minBottom.x);
        Yoga.YGNodeStyleSetMinHeight(bNode, minBottom.y);
        Yoga.YGNodeStyleSetFlexGrow(bNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(bNode, 1);
        Yoga.YGNodeStyleSetWidth(bNode, size.x);

        Yoga.YGNodeStyleSetMaxWidth(lNode, maxLeft.x);
        Yoga.YGNodeStyleSetMaxHeight(lNode, maxLeft.y);
        Yoga.YGNodeStyleSetMinWidth(lNode, minLeft.x);
        Yoga.YGNodeStyleSetMinHeight(lNode, minLeft.y);
        Yoga.YGNodeStyleSetFlexGrow(lNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(lNode, 1);
        Yoga.YGNodeStyleSetMinHeight(lNode, midMaxOfMin);

        Yoga.YGNodeStyleSetMaxWidth(cNode, maxCenter.x);
        Yoga.YGNodeStyleSetMaxHeight(cNode, maxCenter.y);
        Yoga.YGNodeStyleSetMinWidth(cNode, minCenter.x);
        Yoga.YGNodeStyleSetMinHeight(cNode, minCenter.y);
        Yoga.YGNodeStyleSetFlexGrow(cNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(cNode, 1);
        Yoga.YGNodeStyleSetMinHeight(cNode, midMaxOfMin);

        Yoga.YGNodeStyleSetMaxWidth(rNode, maxRight.x);
        Yoga.YGNodeStyleSetMaxHeight(rNode, maxRight.y);
        Yoga.YGNodeStyleSetMinWidth(rNode, minRight.x);
        Yoga.YGNodeStyleSetMinHeight(rNode, minRight.y);
        Yoga.YGNodeStyleSetFlexGrow(rNode, 1);
        Yoga.YGNodeStyleSetFlexShrink(rNode, 1);
        Yoga.YGNodeStyleSetMinHeight(rNode, midMaxOfMin);

        Yoga.nYGNodeCalculateLayout(rootNode, size.x, size.y, Yoga.YGDirectionLTR);

        Vector2f d = new Vector2f(Yoga.YGNodeLayoutGetLeft(mNode), Yoga.YGNodeLayoutGetTop(mNode));

        midRow.set(Yoga.YGNodeLayoutGetLeft(mNode), Yoga.YGNodeLayoutGetTop(mNode), Yoga.YGNodeLayoutGetWidth(mNode), Yoga.YGNodeLayoutGetHeight(mNode));
        top.set(Yoga.YGNodeLayoutGetLeft(tNode), Yoga.YGNodeLayoutGetTop(tNode), Yoga.YGNodeLayoutGetWidth(tNode), Yoga.YGNodeLayoutGetHeight(tNode));
        bottom.set(Yoga.YGNodeLayoutGetLeft(bNode), Yoga.YGNodeLayoutGetTop(bNode), Yoga.YGNodeLayoutGetWidth(bNode), Yoga.YGNodeLayoutGetHeight(bNode));
        left.set(Yoga.YGNodeLayoutGetLeft(lNode) + d.x, Yoga.YGNodeLayoutGetTop(lNode) + d.y, Yoga.YGNodeLayoutGetWidth(lNode), Yoga.YGNodeLayoutGetHeight(lNode));
        right.set(Yoga.YGNodeLayoutGetLeft(rNode) + d.x, Yoga.YGNodeLayoutGetTop(rNode) + d.y, Yoga.YGNodeLayoutGetWidth(rNode), Yoga.YGNodeLayoutGetHeight(rNode));
        center.set(Yoga.YGNodeLayoutGetLeft(cNode) + d.x, Yoga.YGNodeLayoutGetTop(cNode) + d.y, Yoga.YGNodeLayoutGetWidth(cNode), Yoga.YGNodeLayoutGetHeight(cNode));

        Yoga.YGNodeFree(rootNode);
        Yoga.YGNodeFree(mNode);
        Yoga.YGNodeFree(tNode);
        Yoga.YGNodeFree(lNode);
        Yoga.YGNodeFree(cNode);
        Yoga.YGNodeFree(rNode);
        Yoga.YGNodeFree(bNode);
}
```

Do you have any ideas about reason of this behavior?

**Comment by ShchAlexander** [comment] 2017-11-25 14:29
I'll upload gif in higher resolution little bit later

**Comment by ShchAlexander** [comment] 2017-11-25 16:55
Unexpected behavior is white space between nodes if Max and min dimensions are different.

**Comment by Spasi** [comment] 2017-11-25 17:23
Reproduced it, I think it's related to the asymmetry of min/max width/height between `lNode/tNode` and `rNode/bNode`. Looks like a bug to me, I tried to do the same in html/css and it didn't happen there. You may want to report it to [facebook/yoga](https://github.com/facebook/yoga).

**Comment by ShchAlexander** [comment] 2017-11-25 22:48
Created issue on  [facebook/yoga](https://github.com/facebook/yoga) - facebook/yoga#674

**Comment by httpdigest** [comment] 2021-09-16 08:51
Closing this as it is unclear when (and if) this issue is going to be fixed upstream, and we don't want to track all upstream bugs with an additional issue on the LWJGL 3 repo. If it is ever fixed upstream, the next round of upgrading LWJGL 3 bindings will pick it up.

**Closed by httpdigest** 2021-09-16 08:51 UTC
Labels: Type: Bug, 3rd party
