### ISSUE TITLE
Some problems with nanovg text rendering

### ISSUE THREAD

**Issue by ShchAlexander** [LWJGL/lwjgl3#260] opened 2016-12-16 01:54 UTC
I found little issue with nanovg text rendering. 
the issue exist when we are using pointer to the end of the string.

Probably there should be the same result.
I used font with special symmbols to render icons.

<table width="10px">
<thead>
<tr>
<td><b>Pointer to the end is NULL</b></td>
<td><b>Pointer to the end is actually pointer to the end</b></td>
</tr>
</thead>
<tr><td colspan="2">code difference</td></tr>
<tr>
<td><pre lang="java">ByteBuffer byteText = memUTF8(text);
long start = memAddress(byteText);
...
nvgBeginPath(context);
nvgFillColor(context, textColorN);
nnvgText(context, bounds[0], bounds[1], start, 0);</pre></td>
<td><pre lang="java">ByteBuffer byteText = memUTF8(text);
long start = memAddress(byteText);
long end = start + byteText.remaining();
...
nvgBeginPath(context);
nvgFillColor(context, textColorN);
nnvgText(context, bounds[0], bounds[1], start, end);</pre></td>
</tr>
<tr>
<td colspan="2">result difference</td>
</tr>
<tr>
<td><img src="https://cloud.githubusercontent.com/assets/6692636/21248294/1e8f5d70-c347-11e6-9722-9b04f8c3d132.png" width="50"/></td>
<td><img src="https://cloud.githubusercontent.com/assets/6692636/21248303/354b3fde-c347-11e6-9531-1ab1c646d800.png" width="50"/></td>
</tr>
</table>

Probably it could be related to this: 
https://github.com/memononen/nanovg/pull/333

**Comment by Spasi** [comment] 2016-12-16 09:26
Passing `0` to `end` is equivalent to: `end = string + strlen(string);`.

What are the value of `text` and the contents of `byteText`?

The NanoVG demo also uses an icon font (`entypo`), [this is](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nanovg/Demo.java#L122) the code that converts the unicode codepoint to a `ByteBuffer`.

**Comment by ShchAlexander** [comment] 2016-12-16 10:25
Okay, I've edited entypo font and added image symbol for NULL

![image](https://cloud.githubusercontent.com/assets/6692636/21259548/fc277622-c392-11e6-8586-c44cced7d7fe.png)

**Comment by Spasi** [comment] 2016-12-16 12:36
I cannot reproduce this on `3.1.0` or `3.1.1-SNAPSHOT`.

I've also added additional output to `nanovg.c` and have verified that `start, 0` produces the correct `end` value and exactly 1 glyph is being rendered. As expected, using `start, start + byteText.remaining()` produces an `end` value that is one byte off (includes the null-pointer) and there are 2 glyphs rendered (`0xE764` and `0`).

This is exactly the opposite of what you're reporting. Could you a post minimal code sample that reproduces the problem for you?

**Comment by ShchAlexander** [comment] 2016-12-16 13:39
```java
import org.liquidengine.legui.util.IOUtil;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.nanovg.NVGColor;
import org.lwjgl.nanovg.NanoVGGL3;
import org.lwjgl.opengl.GL;

import java.io.IOException;
import java.nio.ByteBuffer;

import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.nanovg.NanoVG.*;
import static org.lwjgl.nanovg.NanoVGGL3.nnvgDeleteGL3;
import static org.lwjgl.nanovg.NanoVGGL3.nvgCreate;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryUtil.*;

public class IssueExample {
    public static final String ENTYPO = "ENTYPO";
    public static final int WIDTH = 400;
    public static final int HEIGHT = 200;
    public static NVGColor bgcolor = NVGColor.create();
    private static volatile boolean running = false;
    private static long context;
    private static String text = new String(Character.toChars(0xE764));
    private static NVGColor textColorN = NVGColor.create();
    private static ByteBuffer fontData;

    public static void main(String[] args) throws IOException {
        if (!GLFW.glfwInit()) {
            throw new RuntimeException("Can't initialize GLFW");
        }
        running = true;
        glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);
        long window = glfwCreateWindow(WIDTH, HEIGHT, "TEST", NULL, NULL);
        glfwShowWindow(window);
        glfwSetKeyCallback(window, (w1, key, code, action, mods) -> running = key == GLFW_KEY_ESCAPE && action != GLFW_RELEASE);
        glfwSetWindowCloseCallback(window, w -> running = false);

        glfwMakeContextCurrent(window);
        GL.createCapabilities();
        glfwSwapInterval(0);
        initializeNanovg();

        while (running) {
            glClearColor(1, 1, 1, 1);
            glViewport(0, 0, WIDTH, HEIGHT);
            glClear(GL_COLOR_BUFFER_BIT);

            renderNanovg();

            glfwPollEvents();
            glfwSwapBuffers(window);
        }

        nnvgDeleteGL3(context);
        glfwDestroyWindow(window);
        glfwTerminate();
    }

    private static void renderNanovg() {
        glDisable(GL_DEPTH_TEST);
        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        nvgBeginFrame(context, WIDTH, HEIGHT, 1);

        renderText();

        nvgEndFrame(context);
        glDisable(GL_BLEND);
        glEnable(GL_DEPTH_TEST);
    }

    private static void renderText() {
        nvgFontSize(context, 100);
        nvgFontFace(context, ENTYPO);
        nvgTextAlign(context, NVG_ALIGN_TOP | NVG_ALIGN_LEFT);

        ByteBuffer byteText = memUTF8(text);
        long start = memAddress(byteText);
        long end = start + byteText.remaining();

        {
            int x = 5;
            int y = 5;
            int w = (WIDTH - 20) / 2;
            int h = HEIGHT - 20;
            renderRect(x, y, w, h);
            renderText(x, y, start, 0);
        }
        {
            int x = 15 + (WIDTH - 20) / 2;
            int y = 10;
            int w = (WIDTH - 20) / 2;
            int h = HEIGHT - 20;
            renderRect(x, y, w, h);
            renderText(x, y, start, end);
        }
        memFree(byteText);
    }

    private static void renderText(int x, int y, long start, long end) {
        nvgBeginPath(context);
        nvgFillColor(context, textColorN);
        nnvgText(context, x, y, start, end);
    }

    private static void renderRect(int x, int y, int w, int h) {
        nvgBeginPath(context);
        nvgRoundedRect(context, x, y, w, h, 0);
        nvgFillColor(context, bgcolor);
        nvgFill(context);
    }

    private static void initializeNanovg() throws IOException {
        int flags = NanoVGGL3.NVG_STENCIL_STROKES | NanoVGGL3.NVG_ANTIALIAS;
        context = nvgCreate(flags);
        fontData = IOUtil.ioResourceToByteBuffer("org/liquidengine/legui/font/entypo_ed.ttf", 1024);
        nvgCreateFontMem(context, ENTYPO, fontData, 0);
        textColorN.r(0); textColorN.g(0); textColorN.b(0); textColorN.a(1);
        bgcolor.r(1);    bgcolor.g(0);    bgcolor.b(0);    bgcolor.a(1);
    }
}
```

[entypo_ed.zip](https://github.com/LWJGL/lwjgl3/files/657272/entypo_ed.zip)

**Comment by Spasi** [comment] 2016-12-16 14:51
The problem in the above code is:

```java
ByteBuffer byteText = memUTF8(text);
long start = memAddress(byteText);
long end = start + byteText.remaining();
```

The `end` value is passed to `nvgText`, but that's not the end of the string. `memUTF8` by default encodes the text with a terminating `\0` byte. This is fine if `nvgText(ctx, x, y, start, NULL)` is used. If an explicit `end` is used, then it must not include the null-terminating byte. The above code can be fixed in two ways:

```java
ByteBuffer byteText = memUTF8(text);
long start = memAddress(byteText);
long end = start + byteText.remaining() - 1;
```

or better:

```java
ByteBuffer byteText = memUTF8(text, false);
long start = memAddress(byteText);
long end = start + byteText.remaining();
```

**Comment by ShchAlexander** [comment] 2016-12-16 14:58
Thank you very much!

**Closed** 2016-12-16 14:59 UTC
Labels: question

**Comment by Spasi** [comment] 2016-12-18 17:12
The next nightly build will apply an auto-size transform to NanoVG functions with an `end` parameter to the end of the string. This means that `end` will automatically receive the value of `memAddress(string) + string.remaining()`. It should hopefully make such functions easier to use and the unsafe versions unnecessary.

- Generated bindings [diff](https://github.com/LWJGL/lwjgl3-generated/commit/6589a930b59cceef77c5369b70ac86e4c594136d).
- NanoVG demo [diff](https://github.com/LWJGL/lwjgl3/commit/aa2df5f9b9a7f92933d738b2dce6c99e690e6222#diff-2a57f3829f92940db80ae516e6f15aa1).

Note that auto-sized string buffers should not include a null-terminating byte.
